# Generated by Django 5.2.6 on 2025-09-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('maritime', 'Maritime'), ('aviation', 'Aviation'), ('multi', 'Multi-modal')], default='road', max_length=10)),
                ('is_baseline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('git_commit', models.CharField(help_text='Short commit hash, e.g. a1b2c3d', max_length=40)),
                ('params_json', models.JSONField(blank=True, null=True)),
                ('metric_name', models.CharField(default='score', max_length=40)),
                ('metric_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='simulations.simulation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
