# Generated by Django 5.2.6 on 2025-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='metric_name',
        ),
        migrations.RemoveField(
            model_name='run',
            name='metric_value',
        ),
        migrations.RemoveField(
            model_name='run',
            name='params_json',
        ),
        migrations.AddField(
            model_name='run',
            name='co2_emissions',
            field=models.FloatField(default=0.0, help_text='Result in tonnes of CO₂'),
            preserve_default=False,
        ),
    ]
