# Generated by Django 5.2.6 on 2025-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_remove_run_metric_name_remove_run_metric_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='git_commit',
            field=models.CharField(db_index=True, help_text='Short commit hash, e.g. a1b2c3d', max_length=40, unique=True),
        ),
    ]
